version: '3.3'

services:
  scheduler-service:
    image: scheduler:latest
    tty: true
    ports:
      - "8089:80"
    environment:
      APP_NAME: scheduler-service
      APP_ENV: development
      PORT: 80
      MONGODB_URL: mongodb://localhost:27017
      DATABASE_NAME: scheduler_development
    networks:
      - app-network

  subscription-billing-engine:
    image: blavkhades/subscription-billing-engine:no-queue
    tty: true
    ports:
      - "7000:80"
    environment:
      APP_NAME: subscription-billing-engine
      APP_ENV: sandbox
      PORT: 80
      REDIS_HOST: 194.99.21.28
      REDIS_PORT: 6378
      REDIS_PASSWORD: Kodobe247?
      RABBITMQ_URL: "amqp://guest:guest@194.99.21.28:5672/sandbox"
  networks:
    - app-network

  #Docker Networks
networks:
  app-network:
    driver: bridge